namespace Nexplant.MC.Core.FaUIs
{
    partial class FSequenceFlow
    {
        /// <summary> 
        /// 필수 디자이너 변수입니다.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// 사용 중인 모든 리소스를 정리합니다.
        /// </summary>
        /// <param name="disposing">관리되는 리소스를 삭제해야 하면 true이고, 그렇지 않으면 false입니다.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }

            // ***
            // myDispose
            // ***
            myDispose(disposing);

            base.Dispose(disposing);
        }

        #region 구성 요소 디자이너에서 생성한 코드

        /// <summary> 
        /// 디자이너 지원에 필요한 메서드입니다. 
        /// 이 메서드의 내용을 코드 편집기로 수정하지 마십시오.
        /// </summary>
        private void InitializeComponent()
        {
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance41 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance42 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance43 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance44 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance46 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance48 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance51 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance26 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance27 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance29 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance30 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance31 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance33 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance35 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance34 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook2 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance77 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance78 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance79 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance80 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance82 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance84 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance87 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook3 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance36 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance37 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance28 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance38 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance32 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance39 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance40 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance70 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook4 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance45 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance47 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance49 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance50 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance52 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook5 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance57 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance53 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance54 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance55 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance56 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance59 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance58 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance61 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance60 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance62 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance64 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance63 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook6 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            this.grdBranch = new Nexplant.MC.Core.FaUIs.FGrid();
            this.grdNegation = new Nexplant.MC.Core.FaUIs.FGrid();
            this.grdSequence = new Nexplant.MC.Core.FaUIs.FGrid();
            this.grdEpilogue = new Nexplant.MC.Core.FaUIs.FGrid();
            this.grdCondition = new Nexplant.MC.Core.FaUIs.FGrid();
            this.grdPrologue = new Nexplant.MC.Core.FaUIs.FGrid();
            ((System.ComponentModel.ISupportInitialize)(this.grdBranch)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.grdNegation)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.grdSequence)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.grdEpilogue)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.grdCondition)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.grdPrologue)).BeginInit();
            this.SuspendLayout();
            // 
            // grdBranch
            // 
            appearance6.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance6.BorderColor = System.Drawing.Color.Silver;
            appearance6.ForeColor = System.Drawing.Color.Black;
            appearance6.TextVAlignAsString = "Middle";
            this.grdBranch.DisplayLayout.Appearance = appearance6;
            this.grdBranch.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.grdBranch.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.grdBranch.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance41.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance41.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance41.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance41.BorderColor = System.Drawing.SystemColors.Window;
            this.grdBranch.DisplayLayout.GroupByBox.Appearance = appearance41;
            appearance42.ForeColor = System.Drawing.SystemColors.GrayText;
            this.grdBranch.DisplayLayout.GroupByBox.BandLabelAppearance = appearance42;
            this.grdBranch.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance43.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance43.BackColor2 = System.Drawing.SystemColors.Control;
            appearance43.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance43.ForeColor = System.Drawing.SystemColors.GrayText;
            this.grdBranch.DisplayLayout.GroupByBox.PromptAppearance = appearance43;
            this.grdBranch.DisplayLayout.MaxColScrollRegions = 1;
            this.grdBranch.DisplayLayout.MaxRowScrollRegions = 1;
            appearance44.BackColor = System.Drawing.SystemColors.Window;
            appearance44.ForeColor = System.Drawing.SystemColors.ControlText;
            this.grdBranch.DisplayLayout.Override.ActiveCellAppearance = appearance44;
            appearance10.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance10.BackColor2 = System.Drawing.Color.LightSteelBlue;
            appearance10.BackGradientStyle = Infragistics.Win.GradientStyle.VerticalBump;
            appearance10.BorderColor = System.Drawing.Color.Silver;
            appearance10.ForeColor = System.Drawing.Color.Black;
            appearance10.TextVAlignAsString = "Middle";
            this.grdBranch.DisplayLayout.Override.ActiveRowAppearance = appearance10;
            this.grdBranch.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.grdBranch.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.grdBranch.DisplayLayout.Override.AllowColSizing = Infragistics.Win.UltraWinGrid.AllowColSizing.Free;
            this.grdBranch.DisplayLayout.Override.AllowColSwapping = Infragistics.Win.UltraWinGrid.AllowColSwapping.NotAllowed;
            this.grdBranch.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.grdBranch.DisplayLayout.Override.AllowMultiCellOperations = Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.None;
            this.grdBranch.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.grdBranch.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.grdBranch.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Solid;
            this.grdBranch.DisplayLayout.Override.BorderStyleHeader = Infragistics.Win.UIElementBorderStyle.Solid;
            this.grdBranch.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance46.BackColor = System.Drawing.SystemColors.Window;
            this.grdBranch.DisplayLayout.Override.CardAreaAppearance = appearance46;
            appearance12.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance12.BorderColor = System.Drawing.Color.Silver;
            appearance12.ForeColor = System.Drawing.Color.Black;
            this.grdBranch.DisplayLayout.Override.CellAppearance = appearance12;
            this.grdBranch.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.grdBranch.DisplayLayout.Override.CellMultiLine = Infragistics.Win.DefaultableBoolean.False;
            this.grdBranch.DisplayLayout.Override.CellPadding = 0;
            this.grdBranch.DisplayLayout.Override.FixedHeaderIndicator = Infragistics.Win.UltraWinGrid.FixedHeaderIndicator.None;
            appearance48.BackColor = System.Drawing.SystemColors.Control;
            appearance48.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance48.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance48.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance48.BorderColor = System.Drawing.SystemColors.Window;
            this.grdBranch.DisplayLayout.Override.GroupByRowAppearance = appearance48;
            appearance13.BackColor = System.Drawing.Color.LightSteelBlue;
            appearance13.BackColor2 = System.Drawing.Color.Lavender;
            appearance13.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance13.BorderColor = System.Drawing.Color.Silver;
            appearance13.ForeColor = System.Drawing.Color.Black;
            appearance13.ForeColorDisabled = System.Drawing.Color.Black;
            appearance13.TextHAlignAsString = "Center";
            appearance13.TextVAlignAsString = "Middle";
            this.grdBranch.DisplayLayout.Override.HeaderAppearance = appearance13;
            this.grdBranch.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.grdBranch.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.Standard;
            this.grdBranch.DisplayLayout.Override.RowAppearance = appearance12;
            this.grdBranch.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.grdBranch.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.Fixed;
            this.grdBranch.DisplayLayout.Override.SelectedAppearancesEnabled = Infragistics.Win.DefaultableBoolean.False;
            appearance15.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance15.BackColor2 = System.Drawing.Color.LightGray;
            appearance15.BackGradientStyle = Infragistics.Win.GradientStyle.VerticalBump;
            appearance15.BorderColor = System.Drawing.Color.Silver;
            appearance15.ForeColor = System.Drawing.Color.Black;
            appearance15.TextVAlignAsString = "Middle";
            this.grdBranch.DisplayLayout.Override.SelectedRowAppearance = appearance15;
            this.grdBranch.DisplayLayout.Override.SelectTypeCell = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.grdBranch.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.grdBranch.DisplayLayout.Override.SelectTypeGroupByRow = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.grdBranch.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance51.BackColor = System.Drawing.SystemColors.ControlLight;
            this.grdBranch.DisplayLayout.Override.TemplateAddRowAppearance = appearance51;
            this.grdBranch.DisplayLayout.Override.TipStyleCell = Infragistics.Win.UltraWinGrid.TipStyle.Hide;
            this.grdBranch.DisplayLayout.Override.WrapHeaderText = Infragistics.Win.DefaultableBoolean.False;
            scrollBarLook1.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.grdBranch.DisplayLayout.ScrollBarLook = scrollBarLook1;
            this.grdBranch.DisplayLayout.Scrollbars = Infragistics.Win.UltraWinGrid.Scrollbars.None;
            this.grdBranch.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.grdBranch.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.grdBranch.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.grdBranch.DisplayLayout.UseFixedHeaders = true;
            this.grdBranch.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.grdBranch.Font = new System.Drawing.Font("Verdana", 8.25F);
            this.grdBranch.Location = new System.Drawing.Point(107, 147);
            this.grdBranch.multiSelected = false;
            this.grdBranch.Name = "grdBranch";
            this.grdBranch.Size = new System.Drawing.Size(200, 36);
            this.grdBranch.TabIndex = 5;
            this.grdBranch.Text = "fGrid1";
            this.grdBranch.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.grdBranch.valueCopyOfClickedCell = true;
            // 
            // grdNegation
            // 
            appearance18.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance18.BorderColor = System.Drawing.Color.Silver;
            appearance18.ForeColor = System.Drawing.Color.Black;
            appearance18.TextVAlignAsString = "Middle";
            this.grdNegation.DisplayLayout.Appearance = appearance18;
            this.grdNegation.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.grdNegation.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.grdNegation.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance24.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance24.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance24.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance24.BorderColor = System.Drawing.SystemColors.Window;
            this.grdNegation.DisplayLayout.GroupByBox.Appearance = appearance24;
            appearance25.ForeColor = System.Drawing.SystemColors.GrayText;
            this.grdNegation.DisplayLayout.GroupByBox.BandLabelAppearance = appearance25;
            this.grdNegation.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance26.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance26.BackColor2 = System.Drawing.SystemColors.Control;
            appearance26.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance26.ForeColor = System.Drawing.SystemColors.GrayText;
            this.grdNegation.DisplayLayout.GroupByBox.PromptAppearance = appearance26;
            this.grdNegation.DisplayLayout.MaxColScrollRegions = 1;
            this.grdNegation.DisplayLayout.MaxRowScrollRegions = 1;
            appearance27.BackColor = System.Drawing.SystemColors.Window;
            appearance27.ForeColor = System.Drawing.SystemColors.ControlText;
            this.grdNegation.DisplayLayout.Override.ActiveCellAppearance = appearance27;
            appearance23.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance23.BackColor2 = System.Drawing.Color.LightSteelBlue;
            appearance23.BackGradientStyle = Infragistics.Win.GradientStyle.VerticalBump;
            appearance23.BorderColor = System.Drawing.Color.Silver;
            appearance23.ForeColor = System.Drawing.Color.Black;
            appearance23.TextVAlignAsString = "Middle";
            this.grdNegation.DisplayLayout.Override.ActiveRowAppearance = appearance23;
            this.grdNegation.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.grdNegation.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.grdNegation.DisplayLayout.Override.AllowColSizing = Infragistics.Win.UltraWinGrid.AllowColSizing.Free;
            this.grdNegation.DisplayLayout.Override.AllowColSwapping = Infragistics.Win.UltraWinGrid.AllowColSwapping.NotAllowed;
            this.grdNegation.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.grdNegation.DisplayLayout.Override.AllowMultiCellOperations = Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.None;
            this.grdNegation.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.grdNegation.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.grdNegation.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Solid;
            this.grdNegation.DisplayLayout.Override.BorderStyleHeader = Infragistics.Win.UIElementBorderStyle.Solid;
            this.grdNegation.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance29.BackColor = System.Drawing.SystemColors.Window;
            this.grdNegation.DisplayLayout.Override.CardAreaAppearance = appearance29;
            appearance30.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance30.BorderColor = System.Drawing.Color.Silver;
            appearance30.ForeColor = System.Drawing.Color.Black;
            this.grdNegation.DisplayLayout.Override.CellAppearance = appearance30;
            this.grdNegation.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.grdNegation.DisplayLayout.Override.CellMultiLine = Infragistics.Win.DefaultableBoolean.False;
            this.grdNegation.DisplayLayout.Override.CellPadding = 0;
            this.grdNegation.DisplayLayout.Override.FixedHeaderIndicator = Infragistics.Win.UltraWinGrid.FixedHeaderIndicator.None;
            appearance31.BackColor = System.Drawing.SystemColors.Control;
            appearance31.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance31.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance31.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance31.BorderColor = System.Drawing.SystemColors.Window;
            this.grdNegation.DisplayLayout.Override.GroupByRowAppearance = appearance31;
            appearance33.BackColor = System.Drawing.Color.LightSteelBlue;
            appearance33.BackColor2 = System.Drawing.Color.Lavender;
            appearance33.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance33.BorderColor = System.Drawing.Color.Silver;
            appearance33.ForeColor = System.Drawing.Color.Black;
            appearance33.ForeColorDisabled = System.Drawing.Color.Black;
            appearance33.TextHAlignAsString = "Center";
            appearance33.TextVAlignAsString = "Middle";
            this.grdNegation.DisplayLayout.Override.HeaderAppearance = appearance33;
            this.grdNegation.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.grdNegation.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.Standard;
            this.grdNegation.DisplayLayout.Override.RowAppearance = appearance30;
            this.grdNegation.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.grdNegation.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.Fixed;
            this.grdNegation.DisplayLayout.Override.SelectedAppearancesEnabled = Infragistics.Win.DefaultableBoolean.False;
            appearance35.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance35.BackColor2 = System.Drawing.Color.LightGray;
            appearance35.BackGradientStyle = Infragistics.Win.GradientStyle.VerticalBump;
            appearance35.BorderColor = System.Drawing.Color.Silver;
            appearance35.ForeColor = System.Drawing.Color.Black;
            appearance35.TextVAlignAsString = "Middle";
            this.grdNegation.DisplayLayout.Override.SelectedRowAppearance = appearance35;
            this.grdNegation.DisplayLayout.Override.SelectTypeCell = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.grdNegation.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.grdNegation.DisplayLayout.Override.SelectTypeGroupByRow = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.grdNegation.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance34.BackColor = System.Drawing.SystemColors.ControlLight;
            this.grdNegation.DisplayLayout.Override.TemplateAddRowAppearance = appearance34;
            this.grdNegation.DisplayLayout.Override.TipStyleCell = Infragistics.Win.UltraWinGrid.TipStyle.Hide;
            this.grdNegation.DisplayLayout.Override.WrapHeaderText = Infragistics.Win.DefaultableBoolean.False;
            scrollBarLook2.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.grdNegation.DisplayLayout.ScrollBarLook = scrollBarLook2;
            this.grdNegation.DisplayLayout.Scrollbars = Infragistics.Win.UltraWinGrid.Scrollbars.None;
            this.grdNegation.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.grdNegation.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.grdNegation.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.grdNegation.DisplayLayout.UseFixedHeaders = true;
            this.grdNegation.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.grdNegation.Font = new System.Drawing.Font("Verdana", 8.25F);
            this.grdNegation.Location = new System.Drawing.Point(211, 111);
            this.grdNegation.multiSelected = false;
            this.grdNegation.Name = "grdNegation";
            this.grdNegation.Size = new System.Drawing.Size(200, 36);
            this.grdNegation.TabIndex = 4;
            this.grdNegation.Text = "fGrid1";
            this.grdNegation.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.grdNegation.valueCopyOfClickedCell = true;
            // 
            // grdSequence
            // 
            appearance1.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance1.BorderColor = System.Drawing.Color.Silver;
            appearance1.ForeColor = System.Drawing.Color.Black;
            appearance1.TextVAlignAsString = "Middle";
            this.grdSequence.DisplayLayout.Appearance = appearance1;
            this.grdSequence.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.grdSequence.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.grdSequence.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance77.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance77.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance77.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance77.BorderColor = System.Drawing.SystemColors.Window;
            this.grdSequence.DisplayLayout.GroupByBox.Appearance = appearance77;
            appearance78.ForeColor = System.Drawing.SystemColors.GrayText;
            this.grdSequence.DisplayLayout.GroupByBox.BandLabelAppearance = appearance78;
            this.grdSequence.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance79.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance79.BackColor2 = System.Drawing.SystemColors.Control;
            appearance79.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance79.ForeColor = System.Drawing.SystemColors.GrayText;
            this.grdSequence.DisplayLayout.GroupByBox.PromptAppearance = appearance79;
            this.grdSequence.DisplayLayout.MaxColScrollRegions = 1;
            this.grdSequence.DisplayLayout.MaxRowScrollRegions = 1;
            appearance80.BackColor = System.Drawing.SystemColors.Window;
            appearance80.ForeColor = System.Drawing.SystemColors.ControlText;
            this.grdSequence.DisplayLayout.Override.ActiveCellAppearance = appearance80;
            appearance2.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance2.BackColor2 = System.Drawing.Color.LightSteelBlue;
            appearance2.BackGradientStyle = Infragistics.Win.GradientStyle.VerticalBump;
            appearance2.BorderColor = System.Drawing.Color.Silver;
            appearance2.ForeColor = System.Drawing.Color.Black;
            appearance2.TextVAlignAsString = "Middle";
            this.grdSequence.DisplayLayout.Override.ActiveRowAppearance = appearance2;
            this.grdSequence.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.grdSequence.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.grdSequence.DisplayLayout.Override.AllowColSizing = Infragistics.Win.UltraWinGrid.AllowColSizing.Free;
            this.grdSequence.DisplayLayout.Override.AllowColSwapping = Infragistics.Win.UltraWinGrid.AllowColSwapping.NotAllowed;
            this.grdSequence.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.grdSequence.DisplayLayout.Override.AllowMultiCellOperations = Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.None;
            this.grdSequence.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.grdSequence.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.grdSequence.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Solid;
            this.grdSequence.DisplayLayout.Override.BorderStyleHeader = Infragistics.Win.UIElementBorderStyle.Solid;
            this.grdSequence.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance82.BackColor = System.Drawing.SystemColors.Window;
            this.grdSequence.DisplayLayout.Override.CardAreaAppearance = appearance82;
            appearance3.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance3.BorderColor = System.Drawing.Color.Silver;
            appearance3.ForeColor = System.Drawing.Color.Black;
            this.grdSequence.DisplayLayout.Override.CellAppearance = appearance3;
            this.grdSequence.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.grdSequence.DisplayLayout.Override.CellMultiLine = Infragistics.Win.DefaultableBoolean.False;
            this.grdSequence.DisplayLayout.Override.CellPadding = 0;
            this.grdSequence.DisplayLayout.Override.FixedHeaderIndicator = Infragistics.Win.UltraWinGrid.FixedHeaderIndicator.None;
            appearance84.BackColor = System.Drawing.SystemColors.Control;
            appearance84.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance84.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance84.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance84.BorderColor = System.Drawing.SystemColors.Window;
            this.grdSequence.DisplayLayout.Override.GroupByRowAppearance = appearance84;
            appearance4.BackColor = System.Drawing.Color.LightSteelBlue;
            appearance4.BackColor2 = System.Drawing.Color.Lavender;
            appearance4.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance4.BorderColor = System.Drawing.Color.Silver;
            appearance4.ForeColor = System.Drawing.Color.Black;
            appearance4.ForeColorDisabled = System.Drawing.Color.Black;
            appearance4.TextHAlignAsString = "Center";
            appearance4.TextVAlignAsString = "Middle";
            this.grdSequence.DisplayLayout.Override.HeaderAppearance = appearance4;
            this.grdSequence.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.grdSequence.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.Standard;
            this.grdSequence.DisplayLayout.Override.RowAppearance = appearance3;
            this.grdSequence.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.grdSequence.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.Fixed;
            this.grdSequence.DisplayLayout.Override.SelectedAppearancesEnabled = Infragistics.Win.DefaultableBoolean.False;
            appearance5.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance5.BackColor2 = System.Drawing.Color.LightGray;
            appearance5.BackGradientStyle = Infragistics.Win.GradientStyle.VerticalBump;
            appearance5.BorderColor = System.Drawing.Color.Silver;
            appearance5.ForeColor = System.Drawing.Color.Black;
            appearance5.TextVAlignAsString = "Middle";
            this.grdSequence.DisplayLayout.Override.SelectedRowAppearance = appearance5;
            this.grdSequence.DisplayLayout.Override.SelectTypeCell = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.grdSequence.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.grdSequence.DisplayLayout.Override.SelectTypeGroupByRow = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.grdSequence.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance87.BackColor = System.Drawing.SystemColors.ControlLight;
            this.grdSequence.DisplayLayout.Override.TemplateAddRowAppearance = appearance87;
            this.grdSequence.DisplayLayout.Override.TipStyleCell = Infragistics.Win.UltraWinGrid.TipStyle.Hide;
            this.grdSequence.DisplayLayout.Override.WrapHeaderText = Infragistics.Win.DefaultableBoolean.False;
            scrollBarLook3.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.grdSequence.DisplayLayout.ScrollBarLook = scrollBarLook3;
            this.grdSequence.DisplayLayout.Scrollbars = Infragistics.Win.UltraWinGrid.Scrollbars.None;
            this.grdSequence.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.grdSequence.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.grdSequence.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.grdSequence.DisplayLayout.UseFixedHeaders = true;
            this.grdSequence.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.grdSequence.Font = new System.Drawing.Font("Verdana", 8.25F);
            this.grdSequence.Location = new System.Drawing.Point(104, 3);
            this.grdSequence.multiSelected = false;
            this.grdSequence.Name = "grdSequence";
            this.grdSequence.Size = new System.Drawing.Size(200, 36);
            this.grdSequence.TabIndex = 0;
            this.grdSequence.Text = "fGrid1";
            this.grdSequence.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.grdSequence.valueCopyOfClickedCell = true;
            // 
            // grdEpilogue
            // 
            appearance36.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance36.BorderColor = System.Drawing.Color.Silver;
            appearance36.ForeColor = System.Drawing.Color.Black;
            appearance36.TextVAlignAsString = "Middle";
            this.grdEpilogue.DisplayLayout.Appearance = appearance36;
            this.grdEpilogue.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.grdEpilogue.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.grdEpilogue.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance19.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance19.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance19.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance19.BorderColor = System.Drawing.SystemColors.Window;
            this.grdEpilogue.DisplayLayout.GroupByBox.Appearance = appearance19;
            appearance20.ForeColor = System.Drawing.SystemColors.GrayText;
            this.grdEpilogue.DisplayLayout.GroupByBox.BandLabelAppearance = appearance20;
            this.grdEpilogue.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance21.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance21.BackColor2 = System.Drawing.SystemColors.Control;
            appearance21.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance21.ForeColor = System.Drawing.SystemColors.GrayText;
            this.grdEpilogue.DisplayLayout.GroupByBox.PromptAppearance = appearance21;
            this.grdEpilogue.DisplayLayout.MaxColScrollRegions = 1;
            this.grdEpilogue.DisplayLayout.MaxRowScrollRegions = 1;
            appearance22.BackColor = System.Drawing.SystemColors.Window;
            appearance22.ForeColor = System.Drawing.SystemColors.ControlText;
            this.grdEpilogue.DisplayLayout.Override.ActiveCellAppearance = appearance22;
            appearance37.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance37.BackColor2 = System.Drawing.Color.LightSteelBlue;
            appearance37.BackGradientStyle = Infragistics.Win.GradientStyle.VerticalBump;
            appearance37.BorderColor = System.Drawing.Color.Silver;
            appearance37.ForeColor = System.Drawing.Color.Black;
            appearance37.TextVAlignAsString = "Middle";
            this.grdEpilogue.DisplayLayout.Override.ActiveRowAppearance = appearance37;
            this.grdEpilogue.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.grdEpilogue.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.grdEpilogue.DisplayLayout.Override.AllowColSizing = Infragistics.Win.UltraWinGrid.AllowColSizing.Free;
            this.grdEpilogue.DisplayLayout.Override.AllowColSwapping = Infragistics.Win.UltraWinGrid.AllowColSwapping.NotAllowed;
            this.grdEpilogue.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.grdEpilogue.DisplayLayout.Override.AllowMultiCellOperations = Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.None;
            this.grdEpilogue.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.grdEpilogue.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.grdEpilogue.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Solid;
            this.grdEpilogue.DisplayLayout.Override.BorderStyleHeader = Infragistics.Win.UIElementBorderStyle.Solid;
            this.grdEpilogue.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance28.BackColor = System.Drawing.SystemColors.Window;
            this.grdEpilogue.DisplayLayout.Override.CardAreaAppearance = appearance28;
            appearance38.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance38.BorderColor = System.Drawing.Color.Silver;
            appearance38.ForeColor = System.Drawing.Color.Black;
            appearance38.TextVAlignAsString = "Middle";
            this.grdEpilogue.DisplayLayout.Override.CellAppearance = appearance38;
            this.grdEpilogue.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.grdEpilogue.DisplayLayout.Override.CellMultiLine = Infragistics.Win.DefaultableBoolean.False;
            this.grdEpilogue.DisplayLayout.Override.CellPadding = 0;
            this.grdEpilogue.DisplayLayout.Override.FixedHeaderIndicator = Infragistics.Win.UltraWinGrid.FixedHeaderIndicator.None;
            appearance32.BackColor = System.Drawing.SystemColors.Control;
            appearance32.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance32.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance32.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance32.BorderColor = System.Drawing.SystemColors.Window;
            this.grdEpilogue.DisplayLayout.Override.GroupByRowAppearance = appearance32;
            appearance39.BackColor = System.Drawing.Color.LightSteelBlue;
            appearance39.BackColor2 = System.Drawing.Color.Lavender;
            appearance39.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance39.BorderColor = System.Drawing.Color.Silver;
            appearance39.ForeColor = System.Drawing.Color.Black;
            appearance39.ForeColorDisabled = System.Drawing.Color.Black;
            appearance39.TextHAlignAsString = "Center";
            appearance39.TextVAlignAsString = "Middle";
            this.grdEpilogue.DisplayLayout.Override.HeaderAppearance = appearance39;
            this.grdEpilogue.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.grdEpilogue.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.Standard;
            this.grdEpilogue.DisplayLayout.Override.RowAppearance = appearance38;
            this.grdEpilogue.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.grdEpilogue.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.Fixed;
            this.grdEpilogue.DisplayLayout.Override.SelectedAppearancesEnabled = Infragistics.Win.DefaultableBoolean.False;
            appearance40.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance40.BackColor2 = System.Drawing.Color.LightGray;
            appearance40.BackGradientStyle = Infragistics.Win.GradientStyle.VerticalBump;
            appearance40.BorderColor = System.Drawing.Color.Silver;
            appearance40.ForeColor = System.Drawing.Color.Black;
            appearance40.TextVAlignAsString = "Middle";
            this.grdEpilogue.DisplayLayout.Override.SelectedRowAppearance = appearance40;
            this.grdEpilogue.DisplayLayout.Override.SelectTypeCell = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.grdEpilogue.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.grdEpilogue.DisplayLayout.Override.SelectTypeGroupByRow = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.grdEpilogue.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance70.BackColor = System.Drawing.SystemColors.ControlLight;
            this.grdEpilogue.DisplayLayout.Override.TemplateAddRowAppearance = appearance70;
            this.grdEpilogue.DisplayLayout.Override.TipStyleCell = Infragistics.Win.UltraWinGrid.TipStyle.Hide;
            this.grdEpilogue.DisplayLayout.Override.WrapHeaderText = Infragistics.Win.DefaultableBoolean.False;
            scrollBarLook4.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.grdEpilogue.DisplayLayout.ScrollBarLook = scrollBarLook4;
            this.grdEpilogue.DisplayLayout.Scrollbars = Infragistics.Win.UltraWinGrid.Scrollbars.None;
            this.grdEpilogue.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.grdEpilogue.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.grdEpilogue.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.grdEpilogue.DisplayLayout.UseFixedHeaders = true;
            this.grdEpilogue.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.grdEpilogue.Font = new System.Drawing.Font("Verdana", 8.25F);
            this.grdEpilogue.Location = new System.Drawing.Point(2, 111);
            this.grdEpilogue.multiSelected = false;
            this.grdEpilogue.Name = "grdEpilogue";
            this.grdEpilogue.Size = new System.Drawing.Size(200, 36);
            this.grdEpilogue.TabIndex = 3;
            this.grdEpilogue.Text = "fGrid1";
            this.grdEpilogue.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.grdEpilogue.valueCopyOfClickedCell = true;
            // 
            // grdCondition
            // 
            this.grdCondition.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            appearance45.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance45.BorderColor = System.Drawing.Color.Silver;
            appearance45.ForeColor = System.Drawing.Color.Black;
            appearance45.TextVAlignAsString = "Middle";
            this.grdCondition.DisplayLayout.Appearance = appearance45;
            this.grdCondition.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.grdCondition.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.grdCondition.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance7.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance7.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance7.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance7.BorderColor = System.Drawing.SystemColors.Window;
            this.grdCondition.DisplayLayout.GroupByBox.Appearance = appearance7;
            appearance9.ForeColor = System.Drawing.SystemColors.GrayText;
            this.grdCondition.DisplayLayout.GroupByBox.BandLabelAppearance = appearance9;
            this.grdCondition.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance8.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance8.BackColor2 = System.Drawing.SystemColors.Control;
            appearance8.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance8.ForeColor = System.Drawing.SystemColors.GrayText;
            this.grdCondition.DisplayLayout.GroupByBox.PromptAppearance = appearance8;
            this.grdCondition.DisplayLayout.MaxColScrollRegions = 1;
            this.grdCondition.DisplayLayout.MaxRowScrollRegions = 1;
            appearance14.BackColor = System.Drawing.SystemColors.Window;
            appearance14.ForeColor = System.Drawing.SystemColors.ControlText;
            this.grdCondition.DisplayLayout.Override.ActiveCellAppearance = appearance14;
            appearance47.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance47.BackColor2 = System.Drawing.Color.LightSteelBlue;
            appearance47.BackGradientStyle = Infragistics.Win.GradientStyle.VerticalBump;
            appearance47.BorderColor = System.Drawing.Color.Silver;
            appearance47.ForeColor = System.Drawing.Color.Black;
            appearance47.TextVAlignAsString = "Middle";
            this.grdCondition.DisplayLayout.Override.ActiveRowAppearance = appearance47;
            this.grdCondition.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.grdCondition.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.grdCondition.DisplayLayout.Override.AllowColSizing = Infragistics.Win.UltraWinGrid.AllowColSizing.Free;
            this.grdCondition.DisplayLayout.Override.AllowColSwapping = Infragistics.Win.UltraWinGrid.AllowColSwapping.NotAllowed;
            this.grdCondition.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.grdCondition.DisplayLayout.Override.AllowMultiCellOperations = Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.None;
            this.grdCondition.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.grdCondition.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.grdCondition.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Solid;
            this.grdCondition.DisplayLayout.Override.BorderStyleHeader = Infragistics.Win.UIElementBorderStyle.Solid;
            this.grdCondition.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance17.BackColor = System.Drawing.SystemColors.Window;
            this.grdCondition.DisplayLayout.Override.CardAreaAppearance = appearance17;
            appearance49.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance49.BorderColor = System.Drawing.Color.Silver;
            appearance49.ForeColor = System.Drawing.Color.Black;
            this.grdCondition.DisplayLayout.Override.CellAppearance = appearance49;
            this.grdCondition.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.grdCondition.DisplayLayout.Override.CellMultiLine = Infragistics.Win.DefaultableBoolean.False;
            this.grdCondition.DisplayLayout.Override.CellPadding = 0;
            this.grdCondition.DisplayLayout.Override.FixedHeaderIndicator = Infragistics.Win.UltraWinGrid.FixedHeaderIndicator.None;
            appearance11.BackColor = System.Drawing.SystemColors.Control;
            appearance11.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance11.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance11.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance11.BorderColor = System.Drawing.SystemColors.Window;
            this.grdCondition.DisplayLayout.Override.GroupByRowAppearance = appearance11;
            appearance50.BackColor = System.Drawing.Color.LightSteelBlue;
            appearance50.BackColor2 = System.Drawing.Color.Lavender;
            appearance50.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance50.BorderColor = System.Drawing.Color.Silver;
            appearance50.ForeColor = System.Drawing.Color.Black;
            appearance50.ForeColorDisabled = System.Drawing.Color.Black;
            appearance50.TextHAlignAsString = "Center";
            appearance50.TextVAlignAsString = "Middle";
            this.grdCondition.DisplayLayout.Override.HeaderAppearance = appearance50;
            this.grdCondition.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.grdCondition.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.Standard;
            this.grdCondition.DisplayLayout.Override.RowAppearance = appearance49;
            this.grdCondition.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.grdCondition.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.Fixed;
            this.grdCondition.DisplayLayout.Override.SelectedAppearancesEnabled = Infragistics.Win.DefaultableBoolean.False;
            appearance52.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance52.BackColor2 = System.Drawing.Color.LightGray;
            appearance52.BackGradientStyle = Infragistics.Win.GradientStyle.VerticalBump;
            appearance52.BorderColor = System.Drawing.Color.Silver;
            appearance52.ForeColor = System.Drawing.Color.Black;
            appearance52.TextVAlignAsString = "Middle";
            this.grdCondition.DisplayLayout.Override.SelectedRowAppearance = appearance52;
            this.grdCondition.DisplayLayout.Override.SelectTypeCell = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.grdCondition.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.grdCondition.DisplayLayout.Override.SelectTypeGroupByRow = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.grdCondition.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance16.BackColor = System.Drawing.SystemColors.ControlLight;
            this.grdCondition.DisplayLayout.Override.TemplateAddRowAppearance = appearance16;
            this.grdCondition.DisplayLayout.Override.TipStyleCell = Infragistics.Win.UltraWinGrid.TipStyle.Hide;
            this.grdCondition.DisplayLayout.Override.WrapHeaderText = Infragistics.Win.DefaultableBoolean.False;
            scrollBarLook5.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.grdCondition.DisplayLayout.ScrollBarLook = scrollBarLook5;
            this.grdCondition.DisplayLayout.Scrollbars = Infragistics.Win.UltraWinGrid.Scrollbars.None;
            this.grdCondition.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.grdCondition.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.grdCondition.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.grdCondition.DisplayLayout.UseFixedHeaders = true;
            this.grdCondition.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.grdCondition.Font = new System.Drawing.Font("Verdana", 8.25F);
            this.grdCondition.Location = new System.Drawing.Point(2, 78);
            this.grdCondition.multiSelected = false;
            this.grdCondition.Name = "grdCondition";
            this.grdCondition.Size = new System.Drawing.Size(409, 34);
            this.grdCondition.TabIndex = 2;
            this.grdCondition.Text = "fGrid1";
            this.grdCondition.UseAppStyling = false;
            this.grdCondition.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.grdCondition.valueCopyOfClickedCell = true;
            // 
            // grdPrologue
            // 
            appearance57.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance57.BorderColor = System.Drawing.Color.Silver;
            appearance57.ForeColor = System.Drawing.Color.Black;
            appearance57.TextVAlignAsString = "Middle";
            this.grdPrologue.DisplayLayout.Appearance = appearance57;
            this.grdPrologue.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.grdPrologue.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.grdPrologue.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance53.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance53.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance53.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance53.BorderColor = System.Drawing.SystemColors.Window;
            this.grdPrologue.DisplayLayout.GroupByBox.Appearance = appearance53;
            appearance54.ForeColor = System.Drawing.SystemColors.GrayText;
            this.grdPrologue.DisplayLayout.GroupByBox.BandLabelAppearance = appearance54;
            this.grdPrologue.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance55.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance55.BackColor2 = System.Drawing.SystemColors.Control;
            appearance55.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance55.ForeColor = System.Drawing.SystemColors.GrayText;
            this.grdPrologue.DisplayLayout.GroupByBox.PromptAppearance = appearance55;
            this.grdPrologue.DisplayLayout.MaxColScrollRegions = 1;
            this.grdPrologue.DisplayLayout.MaxRowScrollRegions = 1;
            appearance56.BackColor = System.Drawing.SystemColors.Window;
            appearance56.ForeColor = System.Drawing.SystemColors.ControlText;
            this.grdPrologue.DisplayLayout.Override.ActiveCellAppearance = appearance56;
            appearance59.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance59.BackColor2 = System.Drawing.Color.LightSteelBlue;
            appearance59.BackGradientStyle = Infragistics.Win.GradientStyle.VerticalBump;
            appearance59.BorderColor = System.Drawing.Color.Silver;
            appearance59.ForeColor = System.Drawing.Color.Black;
            appearance59.TextVAlignAsString = "Middle";
            this.grdPrologue.DisplayLayout.Override.ActiveRowAppearance = appearance59;
            this.grdPrologue.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.grdPrologue.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.grdPrologue.DisplayLayout.Override.AllowColSizing = Infragistics.Win.UltraWinGrid.AllowColSizing.Free;
            this.grdPrologue.DisplayLayout.Override.AllowColSwapping = Infragistics.Win.UltraWinGrid.AllowColSwapping.NotAllowed;
            this.grdPrologue.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.grdPrologue.DisplayLayout.Override.AllowMultiCellOperations = Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.None;
            this.grdPrologue.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.grdPrologue.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.grdPrologue.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Solid;
            this.grdPrologue.DisplayLayout.Override.BorderStyleHeader = Infragistics.Win.UIElementBorderStyle.Solid;
            this.grdPrologue.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance58.BackColor = System.Drawing.SystemColors.Window;
            this.grdPrologue.DisplayLayout.Override.CardAreaAppearance = appearance58;
            appearance61.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance61.BorderColor = System.Drawing.Color.Silver;
            appearance61.ForeColor = System.Drawing.Color.Black;
            this.grdPrologue.DisplayLayout.Override.CellAppearance = appearance61;
            this.grdPrologue.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.grdPrologue.DisplayLayout.Override.CellMultiLine = Infragistics.Win.DefaultableBoolean.False;
            this.grdPrologue.DisplayLayout.Override.CellPadding = 0;
            this.grdPrologue.DisplayLayout.Override.FixedHeaderIndicator = Infragistics.Win.UltraWinGrid.FixedHeaderIndicator.None;
            appearance60.BackColor = System.Drawing.SystemColors.Control;
            appearance60.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance60.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance60.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance60.BorderColor = System.Drawing.SystemColors.Window;
            this.grdPrologue.DisplayLayout.Override.GroupByRowAppearance = appearance60;
            appearance62.BackColor = System.Drawing.Color.LightSteelBlue;
            appearance62.BackColor2 = System.Drawing.Color.Lavender;
            appearance62.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance62.BorderColor = System.Drawing.Color.Silver;
            appearance62.ForeColor = System.Drawing.Color.Black;
            appearance62.ForeColorDisabled = System.Drawing.Color.Black;
            appearance62.TextHAlignAsString = "Center";
            appearance62.TextVAlignAsString = "Middle";
            this.grdPrologue.DisplayLayout.Override.HeaderAppearance = appearance62;
            this.grdPrologue.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.grdPrologue.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.Standard;
            this.grdPrologue.DisplayLayout.Override.RowAppearance = appearance61;
            this.grdPrologue.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.grdPrologue.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.Fixed;
            this.grdPrologue.DisplayLayout.Override.SelectedAppearancesEnabled = Infragistics.Win.DefaultableBoolean.False;
            appearance64.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance64.BackColor2 = System.Drawing.Color.LightGray;
            appearance64.BackGradientStyle = Infragistics.Win.GradientStyle.VerticalBump;
            appearance64.BorderColor = System.Drawing.Color.Silver;
            appearance64.ForeColor = System.Drawing.Color.Black;
            appearance64.TextVAlignAsString = "Middle";
            this.grdPrologue.DisplayLayout.Override.SelectedRowAppearance = appearance64;
            this.grdPrologue.DisplayLayout.Override.SelectTypeCell = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.grdPrologue.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.grdPrologue.DisplayLayout.Override.SelectTypeGroupByRow = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.grdPrologue.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance63.BackColor = System.Drawing.SystemColors.ControlLight;
            this.grdPrologue.DisplayLayout.Override.TemplateAddRowAppearance = appearance63;
            this.grdPrologue.DisplayLayout.Override.TipStyleCell = Infragistics.Win.UltraWinGrid.TipStyle.Hide;
            this.grdPrologue.DisplayLayout.Override.WrapHeaderText = Infragistics.Win.DefaultableBoolean.False;
            scrollBarLook6.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.grdPrologue.DisplayLayout.ScrollBarLook = scrollBarLook6;
            this.grdPrologue.DisplayLayout.Scrollbars = Infragistics.Win.UltraWinGrid.Scrollbars.None;
            this.grdPrologue.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.grdPrologue.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.grdPrologue.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.grdPrologue.DisplayLayout.UseFixedHeaders = true;
            this.grdPrologue.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.grdPrologue.Font = new System.Drawing.Font("Verdana", 8.25F);
            this.grdPrologue.Location = new System.Drawing.Point(2, 39);
            this.grdPrologue.multiSelected = false;
            this.grdPrologue.Name = "grdPrologue";
            this.grdPrologue.Size = new System.Drawing.Size(200, 36);
            this.grdPrologue.TabIndex = 1;
            this.grdPrologue.Text = "fGrid1";
            this.grdPrologue.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.grdPrologue.valueCopyOfClickedCell = true;
            // 
            // FSequenceFlow
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 12F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this.BackColor = System.Drawing.Color.WhiteSmoke;
            this.Controls.Add(this.grdBranch);
            this.Controls.Add(this.grdNegation);
            this.Controls.Add(this.grdSequence);
            this.Controls.Add(this.grdEpilogue);
            this.Controls.Add(this.grdCondition);
            this.Controls.Add(this.grdPrologue);
            this.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.Name = "FSequenceFlow";
            this.Size = new System.Drawing.Size(414, 327);
            this.Load += new System.EventHandler(this.FSequenceFlow_Load);
            this.Paint += new System.Windows.Forms.PaintEventHandler(this.FSequenceFlow_Paint);
            this.ParentChanged += new System.EventHandler(this.FSequenceFlow_ParentChanged);
            ((System.ComponentModel.ISupportInitialize)(this.grdBranch)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.grdNegation)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.grdSequence)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.grdEpilogue)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.grdCondition)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.grdPrologue)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private FGrid grdPrologue;
        private FGrid grdCondition;
        private FGrid grdEpilogue;
        private FGrid grdSequence;
        private FGrid grdNegation;
        private FGrid grdBranch;
    }
}
